#ASSIGNMENT

**Q.1 Compare and contrast NLTK and spaCy in terms of features, ease of use,and performance.**

      --> spaCy is a modern, fast, and production-ready NLP library, while NLTK is an older, comprehensive toolkit, ideal for research, education, and heavy customization. spaCy excels in speed (Cython-based) and accuracy, offering pre-trained models for immediate use, while NLTK requires more manual configuration.

      Features:

     spaCy: Best for Named Entity Recognition (NER), POS tagging, dependency parsing, and word vectors, with specialized pipelines for over 50 languages.

     NLTK: Offers a wider, more diverse range of algorithms, better for prototyping, research, and specific tasks like custom tokenization or stemming.

     Ease of Use:
     
     spaCy: More intuitive and beginner-friendly API designed for rapid development and deployment.

     NLTK: Steeper learning curve; requires building up functionality from foundational components, which is better for learning NLP basics.

     Performance:

     spaCy: Significantly faster and more efficient on large datasets due to its Cython implementation and pre-trained models.

     NLTK: Slower; better suited for smaller datasets, educational purposes, or when specific, non-default algorithms are required.

     ![image.png](
      
     )

     Which to choose?

     Choose spaCy for speed, accuracy, and building production apps.

     Choose NLTK for learning fundamentals, academic research, or when extensive customization is needed.


**Q.2 What is TextBlob and how does it simplify common NLP tasks like sentiment analysis and translation?**

      --> TextBlob is an open-source Python library designed to simplify Natural Language Processing (NLP) tasks by providing an intuitive, user-friendly interface built on top of NLTK and Pattern. It enables rapid prototyping for tasks like sentiment analysis (polarity/subjectivity), translation, tokenization, spelling correction, and part-of-speech tagging with minimal code.

      How TextBlob Simplifies NLP Tasks

      Sentiment Analysis: TextBlob provides immediate, pre-trained sentiment analysis. By calling .sentiment on a text object, it returns a named tuple containing polarity (ranging from -1.0 for negative to 1.0 for positive) and subjectivity (0.0 for objective to 1.0 for subjective).

     Example: TextBlob("I love this!").sentiment-->Sentiment(polarity=0.625, subjectivity=0.6).

     Translation and Language Detection: Using the Google Translate API, TextBlob allows for easy language detection and translation with single method calls like detect_language() and translate(to='es').

     Text Processing Pipeline: It streamlines preprocessing, such as converting text into words/sentences (tokenization), noun phrase extraction, and spelling correction (.correct()).

     Ease of Use: It treats text as Python strings that have learned NLP, allowing for straightforward manipulations.

     Key Features:

     Installation: Installed via pip install textblob and python -m textblob.download_corpora.

     Performance: It is generally faster than NLTK for basic tasks and ideal for applications with limited computational resources.

     Flexibility: While it includes pre-trained models, it also supports custom classifiers (e.g., Naive Bayes).

**Q.3 Explain the role of Standford NLP in academic and industry NLP Projects.**

      --> The Stanford NLP Group, led by faculty like Christopher Manning, is a pivotal force in AI, developing industry-standard tools like CoreNLP (Java-based) and Stanza (Python-based). It bridges academic research with practical application by providing high-performance, multilingual, and deep-learning-based tools for tokenization, parsing, Named Entity Recognition (NER), and sentiment analysis, supporting over 70 languages.

      Key Roles in Academia

      Fundamental Research: Stanford conducts pioneering research in computational linguistics, deep learning, and, notably, neural machine translation.

     Standardized Tools: It develops foundational resources such as GloVe (Global Vectors for Word Representation) and the SNLI corpus for Natural Language Inference.

     Education: The group offers renowned courses (e.g., CS224n) that shape the curriculum for AI/NLP education worldwide.

     Key Roles in Industry

     Robust Preprocessing: Industry professionals rely on CoreNLP for building robust, high-performance pipelines for text analytics, sentiment analysis, and information extraction.

     Stanford CoreNLP: A Java suite known for its reliability in production environments.

     Stanza: A python natural language processing library that supports 70+ languages.

     GloVe: A model for distributed word representation.

     SUTime: A tool for recognizing and normalizing time expressions.

**Q.4 Describe the architecture and functioning of a Recurrent Natural Network (RNN).**

      --> Recurrent Neural Networks (RNNs) are a class of artificial neural networks designed to process sequential data (e.g., text, audio, time-series) by using internal "memory" to retain information from previous inputs. Unlike feedforward networks, RNNs include feedback loops within their hidden layers, allowing information to persist and influence future outputs, enabling them to handle inputs of variable length.

      Architecture of an RNN

      The architecture of a standard RNN is built upon recurrent neurons, which can be visualized as a chain-like structure.

      Hidden State (): The core memory component that summarizes the sequence information seen so far.

      Feedback Loops (Recurrence): At each time step (), the hidden layer receives two inputs: the current input () and the hidden state from the previous time step ().

      Parameter Sharing: The same weights () are shared across all time steps, reducing model complexity and allowing it to recognize patterns regardless of their position in the sequence.

      Unfolded Structure: When visualized over time, the network "unfolds" into a chain, where each step corresponds to a specific point in time ().

      Functioning and Operation

      1. Input: The network receives input for the current time step.

      2. Hidden State Update: The new hidden state h1 is computed using the formula:h1 = tanh(Wxhx1 + Whhh-1 + bh). This uses the current input and the previous hidden state (memory).

      3. Output Generation: The output y1 is generated using the new hidden state, often via a softmax function: y1 = softmax(Whyh1 + by).

      4. Looping: The new hidden state h1 is passed as input to the next time step, enabling temporal memory.

      Training: Backpropagation Through Time (BPTT)

      RNNs are trained using a method called Backpropagation Through Time (BPTT).

      Forward Pass: Data is fed through the sequence, and hidden states are calculated for all time steps.

      Loss Calculation: The error is calculated at each step (or at the end of the sequence).

      Backward Pass: The errors are propagated backward through time (from step T back to 1) to update the weights based on all preceding steps.

      Challenges and Variations

      Standard RNNs struggle with long-term dependencies due to the vanishing and exploding gradient problems, where signals from long ago disappear, causing the network to "forget".

      LSTM (Long Short-Term Memory): Addresses this with a cell state and three gates (input, forget, output) to manage memory effectively.

      GRU (Gated Recurrent Unit): A simpler alternative to LSTM that uses update and reset gates, allowing for faster training.

      Bidirectional RNNs (BRNN): Process data in both forward and backward directions, allowing the network to use both past and future context for predictions.

      Key Applications

      Natural Language Processing (NLP): Sentiment analysis, text generation, machine translation.

     Time-Series Forecasting: Stock price prediction, weather forecasting.

     Speech Recognition: Converting audio into text.

**Q.5 What is the key difference between LSTM and GRU networks in NLP applications?**

      --> The key difference between LSTM and GRU in NLP is that LSTM uses three gates (input, forget, output) and a separate cell state for complex, long-term memory, while GRU uses two gates (reset, update) and merges the cell/hidden states for faster, more efficient training.

      Key Differences and Applications:

      Architecture Complexity: LSTM has a more complex structure, making it better for capturing long-term dependencies in long, complex sequences.

      Computational Efficiency: GRU is simpler, has fewer parameters, and trains faster, making it better suited for smaller datasets or resource-constrained environments.

      Performance: LSTMs are generally preferred for complex, long-range dependencies (e.g., machine translation), whereas GRUs provide similar performance on shorter sequences with faster, more efficient training (e.g., sentiment analysis).

      ![image.png](
        
      )

      Ultimately, both are effective at tackling vanishing gradient problems in RNNs, and the choice depends on whether the task requires maximum memory capacity (LSTM) or higher computational efficiency (GRU).

**Q.6 Write a Python program using TextBlob to perform sentiment analysis on the following paragraph of text:**

**“I had a great experience using the new mobile banking app. The interface is intuitive, and customer support was quick to resolve my issue. However, the app did crash once during a transaction, which was frustrating"**

**Your program should print out the polarity and subjectivity scores.**


In [1]:
# Import TextBlob
from textblob import TextBlob

# Paragraph text
text = """I had a great experience using the new mobile banking app.
The interface is intuitive, and customer support was quick to resolve my issue.
However, the app did crash once during a transaction, which was frustrating."""

# Create TextBlob object
analysis = TextBlob(text)

# Get sentiment
polarity = analysis.sentiment.polarity
subjectivity = analysis.sentiment.subjectivity

# Print results
print("Polarity Score:", polarity)
print("Subjectivity Score:", subjectivity)

Polarity Score: 0.21742424242424244
Subjectivity Score: 0.6511363636363636


**Q.7  Given the sample paragraph below, perform string tokenization and frequency distribution using Python and NLTK:**

**“Natural Language Processing (NLP) is a fascinating field that combines linguistics,computer science, and artificial intelligence. It enables machines to understand, interpret, and generate human language. Applications of NLP include chatbots, sentiment analysis, and machine translation. As technology advances, the role of NLP in modern solutions is becoming increasingly critical.”**

In [3]:
# Import required libraries
import nltk
from nltk.tokenize import word_tokenize
from nltk.probability import FreqDist

# Download tokenizer (run once)
nltk.download('punkt')
nltk.download('punkt_tab') # Added to resolve the LookupError

# Sample paragraph
text = """Natural Language Processing (NLP) is a fascinating field that combines linguistics,
computer science, and artificial intelligence. It enables machines to understand,
interpret, and generate human language. Applications of NLP include chatbots,
sentiment analysis, and machine translation. As technology advances, the role of NLP
in modern solutions is becoming increasingly critical."""

# Tokenization (split text into words)
tokens = word_tokenize(text)

# Convert to lowercase and remove punctuation
words = [word.lower() for word in tokens if word.isalpha()]

# Frequency Distribution
freq_dist = FreqDist(words)

# Print tokens
print("Tokens:")
print(words)

# Print frequency distribution
print("\nFrequency Distribution:")
for word, freq in freq_dist.items():
    print(word, ":", freq)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


Tokens:
['natural', 'language', 'processing', 'nlp', 'is', 'a', 'fascinating', 'field', 'that', 'combines', 'linguistics', 'computer', 'science', 'and', 'artificial', 'intelligence', 'it', 'enables', 'machines', 'to', 'understand', 'interpret', 'and', 'generate', 'human', 'language', 'applications', 'of', 'nlp', 'include', 'chatbots', 'sentiment', 'analysis', 'and', 'machine', 'translation', 'as', 'technology', 'advances', 'the', 'role', 'of', 'nlp', 'in', 'modern', 'solutions', 'is', 'becoming', 'increasingly', 'critical']

Frequency Distribution:
natural : 1
language : 2
processing : 1
nlp : 3
is : 2
a : 1
fascinating : 1
field : 1
that : 1
combines : 1
linguistics : 1
computer : 1
science : 1
and : 3
artificial : 1
intelligence : 1
it : 1
enables : 1
machines : 1
to : 1
understand : 1
interpret : 1
generate : 1
human : 1
applications : 1
of : 2
include : 1
chatbots : 1
sentiment : 1
analysis : 1
machine : 1
translation : 1
as : 1
technology : 1
advances : 1
the : 1
role : 1
in : 1
m

**Q.8 Implement a basic LSTM model in Keras for a text classification task using the following dummy dataset. Your model should classify sentences as either positive (1) or negative (0).**

**# Dataset texts = [ “I love this project”, #Positive**
**“This is an amazing experience”, #Positive**
**“I hate waiting in line”, #Negative**
**“This is the worst service”, #Negative**
**“Absolutely fantastic!” #Positive**
]
**

**labels = [1, 1, 0, 0, 1]**

**Preprocess the text, tokenize it, pad sequences, and build an LSTM model to train on this data. You may use Keras with TensorFlow backend.**

In [4]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

texts = [
"I love this project",            # Positive
"This is an amazing experience",  # Positive
"I hate waiting in line",         # Negative
"This is the worst service",      # Negative
"Absolutely fantastic!"           # Positive
]

labels = [1, 1, 0, 0, 1]

tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)

sequences = tokenizer.texts_to_sequences(texts)

print("Sequences:", sequences)

max_length = max(len(seq) for seq in sequences)

padded_sequences = pad_sequences(sequences, maxlen=max_length, padding='post')

print("Padded Sequences:\n", padded_sequences)

vocab_size = len(tokenizer.word_index) + 1

model = Sequential()

model.add(Embedding(input_dim=vocab_size, output_dim=16, input_length=max_length))

model.add(LSTM(16))

model.add(Dense(1, activation='sigmoid'))

model.fit(
    padded_sequences,
    np.array(labels),
    epochs=20,
    verbose=1
)

test_sentence = ["I love this service"]

test_seq = tokenizer.texts_to_sequences(test_sentence)
test_pad = pad_sequences(test_seq, maxlen=max_length, padding='post')

prediction = model.predict(test_pad)

print("Prediction:", prediction)

model.summary()

Sequences: [[2, 4, 1, 5], [1, 3, 6, 7, 8], [2, 9, 10, 11, 12], [1, 3, 13, 14, 15], [16, 17]]
Padded Sequences:
 [[ 2  4  1  5  0]
 [ 1  3  6  7  8]
 [ 2  9 10 11 12]
 [ 1  3 13 14 15]
 [16 17  0  0  0]]


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


ValueError: You must call `compile()` before using the model.

**Q.9 Using spaCy, build a simple NLP pipeline that includes tokenization lemmatization, and entity recognition. Use the following paragraph as your dataset: “Homi Jehangir Bhaba was an Indian nuclear physicist who played a key role in the development of India’s atomic energy program. He was the founding director of the Tata Institute of Fundamental Research (TIFR) and was instrumental in establishing the Atomic Energy Commission of India.” Write a Python program that processes this text using spaCy, then prints tokens, their lemmas, and any named entities found.**

In [5]:
# Install spaCy and download English model (run once)
# pip install spacy
# python -m spacy download en_core_web_sm

import spacy

nlp = spacy.load("en_core_web_sm")

text = """
Homi Jehangir Bhaba was an Indian nuclear physicist who played a key role in the
development of India’s atomic energy program. He was the founding director of the Tata
Institute of Fundamental Research (TIFR) and was instrumental in establishing the
Atomic Energy Commission of India.
"""

doc = nlp(text)

print("Tokens and Lemmas:\n")

for token in doc:
    print(f"Token: {token.text}  |  Lemma: {token.lemma_}")

print("\nNamed Entities:\n")

for ent in doc.ents:
    print(f"Entity: {ent.text}  |  Label: {ent.label_}")

import spacy

# Load English model
nlp = spacy.load("en_core_web_sm")

text = """
Homi Jehangir Bhaba was an Indian nuclear physicist who played a key role in the
development of India’s atomic energy program. He was the founding director of the Tata
Institute of Fundamental Research (TIFR) and was instrumental in establishing the
Atomic Energy Commission of India.
"""

# Process text
doc = nlp(text)

# Tokenization and Lemmatization
print("Tokens and Lemmas:\n")
for token in doc:
    print(f"{token.text}  ->  {token.lemma_}")

# Named Entity Recognition
print("\nNamed Entities:\n")
for ent in doc.ents:
    print(f"{ent.text}  ->  {ent.label_}")



Tokens and Lemmas:

Token: 
  |  Lemma: 

Token: Homi  |  Lemma: Homi
Token: Jehangir  |  Lemma: Jehangir
Token: Bhaba  |  Lemma: Bhaba
Token: was  |  Lemma: be
Token: an  |  Lemma: an
Token: Indian  |  Lemma: indian
Token: nuclear  |  Lemma: nuclear
Token: physicist  |  Lemma: physicist
Token: who  |  Lemma: who
Token: played  |  Lemma: play
Token: a  |  Lemma: a
Token: key  |  Lemma: key
Token: role  |  Lemma: role
Token: in  |  Lemma: in
Token: the  |  Lemma: the
Token: 
  |  Lemma: 

Token: development  |  Lemma: development
Token: of  |  Lemma: of
Token: India  |  Lemma: India
Token: ’s  |  Lemma: ’s
Token: atomic  |  Lemma: atomic
Token: energy  |  Lemma: energy
Token: program  |  Lemma: program
Token: .  |  Lemma: .
Token: He  |  Lemma: he
Token: was  |  Lemma: be
Token: the  |  Lemma: the
Token: founding  |  Lemma: found
Token: director  |  Lemma: director
Token: of  |  Lemma: of
Token: the  |  Lemma: the
Token: Tata  |  Lemma: Tata
Token: 
  |  Lemma: 

Token: Institute  |  Le

**Q.10 You are working on a chatbot for a mental health platform. Explain how you would leverage LSTM or GRU networks along with libraries like spaCy or Stanford NLP to understand and respond to user input effectively. Detail your architecture, data preprocessing pipeline, and any ethical considerations.**

      --> A mental health chatbot can use Long Short-Term Memory or Gated Recurrent Unit networks along with NLP libraries like spaCy or Stanford CoreNLP to understand user messages and provide supportive responses. The system processes user input through several stages to detect emotions, intent, and context before generating a reply.

     Key points:

     Architecture: User input → NLP preprocessing (spaCy/Stanford NLP) → LSTM/GRU model for intent and emotion detection → response generation module.

     Data preprocessing: Clean text, perform tokenization and lemmatization, convert words to numerical sequences, and apply padding and embeddings.

     Model working: LSTM/GRU analyzes the sequence of words to understand context and classify user intent such as stress, sadness, or anxiety.

     Response generation: The chatbot selects empathetic responses from predefined templates or a response database.

     Ethical considerations: Ensure user privacy, clearly inform users it is an AI system, detect crisis situations, and recommend professional help when necessary.